### PR TITLE
Avoid UB arising from adding 1 to a null pointer

### PR DESCRIPTION
**Pull request by tonyelewis**
Attempt to address the UB described in dtschump/CImg#250

Attempt to keep to the original style of the code as far as possible

### CODE REVIEW

**Comment by dtschump** [comment]
Thanks for the suggestion.
I've recently discovered `std::strrchr()` which seems to be a perfect fit here.
I'll rather propose then:
~~~~
    inline const char *split_filename(const char *const filename, char *const body=0) {
      if (!filename) { if (body) *body = 0; return 0; }
      const char * p = std::strrchr(filename,'.');
      if (!p || std::strchr(p,'/') || std::strchr(p,'\\')) { // No extension.
        if (body) std::strcpy(body,filename);
        return filename + std::strlen(filename);
      }
      const unsigned int l = (unsigned int)(p - filename);
      if (body) { if (l) std::memcpy(body,filename,l); body[l] = 0; }
      return p + 1;
    }
~~~~

**Comment by tonyelewis** [comment]
Oh yes - that's better than my suggestion. Shall I modify the PR accordingly or do you just want to do it yourself?

**Comment by dtschump** [comment]
I've already pushed a commit. Maybe we can remove the PR ?
I'll add your name to the contributors, of course :)

**Comment by tonyelewis** [comment]
Yep. Great. Thanks.

**Pull request closed without merging**
