### PR TITLE
Fix strict-overflow warning in cimg_for1()

### PR DESCRIPTION
**Pull request by cryptomilk**
'i' will never be negative so use size_t.

### CODE REVIEW

**Comment by dtschump** [comment]
That doesn't sound a good idea to me.
Basically `size_t` is some kind of `unsigned int`, which means that if you do signed calculations in your loop, you may get a lot of troubles if you are not careful enough, like in this toy example:
~~~~
  CImg<> img(300,300);
  cimg_forXY(img,x,y) {
    img(x,y) = x - img.width()/2;
  }
  img.display();
~~~~
Here, `img(x,y)` will be never negative (`unsigned` calculation), which is really not natural.

**Comment by cryptomilk** [comment]
As `i` is only increased, it can't be negative. If `bound` can be negative, you should check that before passing it to the loop! Then convert to unsigned for the loop.

The warning is:

```CImg.h:845:45: warning: assuming signed overflow does not occur when assuming that (X + c) >= X is always true [-Wstrict-overflow]```

This is coming from the optimizer. It means that it is not able to optimize the code. As this seems to an essential macro you should fix this so that the optimizer can do its job. A few lines down are more loops working with int instead of unsigned it.

**Comment by cryptomilk** [comment]
The compiler options are: `-O3 -Wstrict-overflow=2` to get the warning.

I suggest to let the configure tool (cmake) check if the compiler supports -Wstrict-overflow' and then enable `-Werror=strict-overflow -Wstrict-overflow=2` ;-)

**Comment by cryptomilk** [comment]
Then it is probably better to have a function instead of a macro?

```
inline int cimg_for1(int bound)
{
    size_t i;
    for (i = 0; i < (size_t)bound; i++);
    if (i > INT_MAX) {
        return -1;
    }
    return (int)i;
}

#define cimg_forX(img,x) x = cimg_for1((img)._width)
```

**Comment by dtschump** [comment]
No, it's a macro because it's basically a simple way to write loops over images (`for(y..) for (x..) { .. }`),
like this : 
~~~~
cimg_forXY(img,x,y) { img(x,y) = x + y; }
~~~~
Another way to do it would be to use C++ iterators, but as always with C++ iterators, it would be just a pain to use.

**Comment by cryptomilk** [comment]
Yes, but the cimg_for1() can be an inline function, or not? It doesn't look like it is used directly. So making it an line function would just mean changing the other macros.

Sorry, I don't have any clue about this image stuff, I'm just trying to fix this. As a fix would mean the warnings go away and the optimizer can actually optimize the code.

If you can't fix it or there is no simple solution to it feel free to close it :-)

**Comment by dtschump** [comment]
I don't think there is an easy solution indeed, except disabling this particular warning for g++ :)

**Pull request closed without merging**
