### PR TITLE
add custom mesh structure interface

### PR DESCRIPTION
**Pull request by UlysseV**

### CODE REVIEW

**Comment by dtschump** [comment]
Nevermind, I'll be able to make a C++98-compliant code that reuse your idea.
I'm a bit sorry about keeping compatibility with older versions of C++, but CImg is widely used and I cannot just break things with new versions when I can avoid it :)

**Comment by UlysseV** [comment]
Ho, yes, the lambdas.
Sorry, I'm used to syntactic sugar.
I'll replace those with proper functors.

**Comment by dtschump** [comment]
I'm actually almost finished with my version, so please don't waste your time :)

**Comment by UlysseV** [comment]
Fine. Thank you for your time !

**Comment by dtschump** [comment]
It should be OK now.
Not as elegant as with your lambdas, but should work the same, even for C++98.

**Pull request closed without merging**
